# Generated by Django 3.0.8 on 2020-07-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='genero',
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.TextField(max_length=500),
        ),
    ]
